name: Tests and builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: lint
    uses: ./.github/workflows/lint.yml
   
  playwright:
    name: playwright
    needs: lint
    uses: ./.github/workflows/playwright.yml
  
  builds:
    name: builds
    needs: playwright
    uses: ./.github/workflows/canBuild.yml
